// Inventario de morfemas para las gafas de Geruzak.
// [mota, forma, explicación, sección de la guía]
export const MOTA = {
  erro: ['Erroa', 'raíz · lo que significa la palabra', 'raíz'],
  det:  ['Mugatzailea', 'artículo y número', 'artículo'],
  kasu: ['Kasua', 'caso · qué papel hace en la frase', 'caso'],
  lot:  ['Lotura', 'letra de enlace', 'enlace'],
  asp:  ['Aspektua', 'forma del verbo · tiempo y aspecto', 'aspecto'],
  pers: ['Pertsona', 'persona del verbo · quién, a quién, qué', 'persona'],
  erat: ['Eratorria', 'grado o palabra derivada', 'derivación'],
  part: ['Partikula', 'negación, pregunta o subordinación', 'partícula']
};
export const M = {
  // ── sintagma nominal
  DET:    ['det', '-a', 'Artículo singular: «el / la». Se pega al final del grupo (etxe zuri-a). Si la palabra ya acaba en -a, no se duplica.', 's3'],
  DETPL:  ['det', '-ak', 'Artículo plural en NOR: «los / las» (etxe-ak).', 's3'],
  PL:     ['det', '-e-', 'Plural dentro de un caso: etxe-e-k, etxe-e-i, etxe-e-ta-n.', 's5'],
  TA:     ['lot', '-ta-', 'Enlace de los casos de lugar en plural y sin artículo: etxe-ta-n, etxe-e-ta-n.', 's5'],
  LOTE:   ['lot', '-e-', 'Letra de enlace tras consonante: lagun-e-an, Irun-e-ra.', 's5'],
  LOTR:   ['lot', '-r-', 'Letra de enlace entre dos vocales: etxe-r-i, etxea-r-en.', 's5'],
  // ── casos
  NORK:   ['kasu', '-k', 'NORK (ergativo): sujeto de un verbo con objeto directo, el que lleva auxiliar du / dut / duzu…', 's6'],
  NORI:   ['kasu', '-i', 'NORI (dativo): «a …», el objeto indirecto.', 's6'],
  NOREN:  ['kasu', '-en', 'NOREN (genitivo): «de …» de posesión. Va delante de lo poseído.', 's6'],
  NORENTZAT: ['kasu', '-entzat', 'NORENTZAT: «para …», el destinatario.', 's5'],
  NOREKIN:['kasu', '-ekin', 'NOREKIN (sociativo): «con …», la compañía.', 's6'],
  NON:    ['kasu', '-n', 'NON (inesivo): «en …», dónde está algo, en el espacio o en el tiempo.', 's6'],
  NONSG:  ['kasu', '-an', 'NON en singular: «en el / la …» (etxe-an; tras consonante, lagun-e-an).', 's5'],
  NORA:   ['kasu', '-ra', 'NORA (adlativo): «a / hacia …», a dónde se va.', 's6'],
  NONDIKD:['kasu', '-dik', 'NONDIK tras -n: -tik se vuelve -dik (Irun-dik, non-dik, hemen-dik).', 's6'],
  NORENRE:['kasu', 're-', 'Genitivo de los pronombres personales: ni → nire, zu → zure, gu → gure («mi, tu, nuestro»).', 's6'],
  GATIK:  ['kasu', '-gatik', 'Causal «por …»: zer-gatik = por qué, horre-gatik = por eso.', 's8'],
  EK:     ['det', '-ek', 'Plural de demostrativos y pronombres: hau-ek, zu-ek. Vale para NOR y para NORK.', 's4'],
  NONDIK: ['kasu', '-tik', 'NONDIK (ablativo): «desde / de …», de dónde se viene.', 's6'],
  NONGO:  ['kasu', '-ko', 'NONGO: «de …» de lugar o de tiempo (procedencia, ubicación): Bilbo-ko, gaur-ko.', 's6'],
  NONGOG: ['kasu', '-go', 'NONGO tras -n o -l: -ko se vuelve -go (Irun-go, non-go).', 's6'],
  INST:   ['kasu', '-z', 'Instrumental: medio («en autobús»), materia («de madera») o tema («sobre…»).', 's6'],
  PART:   ['kasu', '-(r)ik', 'Partitivo: en frases negativas y preguntas, «ningún / algún». Sustituye al artículo.', 's15'],
  GAN:    ['kasu', '-gan', 'NORENGAN: «en» una persona o animal. Con seres vivos los casos de lugar se apoyan en el genitivo.', 's7'],
  GANA:   ['kasu', '-gana', 'NORENGANA: «a» una persona (a su casa, a donde está).', 's7'],
  GANDIK: ['kasu', '-gandik', 'NORENGANDIK: «de / desde» una persona.', 's7'],
  TAZ:    ['kasu', '-taz', 'Instrumental de los pronombres (zure-taz): «de / sobre ti».', 's6'],
  // ── grado y derivación
  COMP:   ['erat', '-ago', 'Comparativo: «más …» (handi-ago-a = más grande).', 's16'],
  SUP:    ['erat', '-en', 'Superlativo: «el más …» (handi-en-a = el más grande).', 's16'],
  EXC:    ['erat', '-egi', 'Excesivo: «demasiado …» (handi-egi-a).', 's16'],
  ORD:    ['erat', '-garren', 'Ordinal: hiru-garren = tercero.', 's17'],
  LE:     ['erat', '-le / -tzaile', 'Quien hace la acción: ikas-le = estudiante, galde-tzaile = el que pregunta.', 's3'],
  KI:     ['erat', '-ki', 'Forma adverbios de modo: ozen-ki = en voz alta.', 's6'],
  DUN:    ['erat', '-dun', '«Que tiene»: bizi-dun = que tiene vida, ser vivo.', 's7'],
  TAR:    ['erat', '-tar', 'Origen o pertenencia: Bilbo-tar = de Bilbao.', 's9'],
  TXO:    ['erat', '-txo / -xka', 'Diminutivo: ipuin-xka = cuentecillo.', 's2'],
  ERO:    ['erat', '-ero', 'Distributivo: «cada …» (egun-ero = cada día).', 's17'],
  PEN:    ['erat', '-pen / -keta / -kuntza', 'Forma nombres de acción o proceso: ezezta-pen = negación, mendera-kuntza = subordinación.', 's19'],
  BIDE:   ['erat', 'bide', 'bide = camino, vía; en compuestos, «sistema»: deklina-bide-a = la declinación.', 's5'],
  // ── verbo: aspecto y formas no personales
  PERF:   ['asp', '-tu / -du / -i / -n', 'Participio (aspecto perfecto): «hecho, venido». Con auxiliar: «he hecho, he venido».', 's11'],
  HAB:    ['asp', '-t(z)en', 'Habitual: «hago, suelo hacer». Con ari izan: «estar haciendo».', 's11'],
  FUT:    ['asp', '-ko / -go', 'Futuro: participio + -ko (-go tras -n): «haré, vendré».', 's11'],
  TAEG:   ['asp', '-ta', 'Participio de estado: «(estando) hecho»: nekatu-ta = cansado.', 's11'],
  TZE:    ['asp', '-t(z)e', 'Nombre del verbo, «el hacer»: base de -t(z)eko, -t(z)era, -t(z)ea.', 's14'],
  TEKO:   ['asp', '-t(z)eko', 'Finalidad: «para hacer» (ikas-teko = para estudiar).', 's19'],
  TERA:   ['asp', '-t(z)era', 'Con verbos de movimiento: «a hacer» (eros-tera noa = voy a comprar).', 's14'],
  // ── auxiliares y verbos sintéticos: raíces
  IZANR:  ['erro', 'izan', 'Raíz de izan: ser, estar; también el auxiliar de los verbos sin objeto directo.', 's9'],
  UKANR:  ['erro', '-u-', 'Raíz de ukan (*edun): tener; también el auxiliar de los verbos con objeto directo.', 's10'],
  ZAIR:   ['erro', 'zai-', 'Raíz del auxiliar NOR-NORI (zait, zaizu…): «me gusta, me pasa».', 's13'],
  EGONR:  ['erro', '-ago- / -aude-', 'Presente de egon: estar (estado o lugar).', 's12'],
  JOANR:  ['erro', '-oa-', 'Presente de joan: ir.', 's12'],
  ETORRIR:['erro', '-ator- / -atoz-', 'Presente de etorri: venir.', 's12'],
  IBILIR: ['erro', '-abil-', 'Presente de ibili: andar, estar (haciendo algo).', 's12'],
  JAKINR: ['erro', '-aki-', 'Presente de jakin: saber.', 's12'],
  EDUKIR: ['erro', '-auka- / -auzka-', 'Presente de eduki: tener. Con -z- (dauzka-) el objeto es plural.', 's12'],
  EZANR:  ['erro', '-ezake-', 'Potencial: «puedes (hacer)» (dezakezu).', 's14'],
  // ── personas y concordancia
  P3:     ['pers', 'd-', 'Presente con NOR de 3.ª persona (él, ella, eso, lo, la…).', 's9'],
  P3PAST: ['pers', 'z-', 'Pasado con 3.ª persona.', 's9'],
  PNI:    ['pers', 'n-', 'ni · yo.', 's9'],
  PZU:    ['pers', 'z-', 'zu · tú / usted.', 's9'],
  PGU:    ['pers', 'g-', 'gu · nosotros / nosotras.', 's9'],
  PZUPAST:['pers', 'zen-', 'zuk en pasado: tú.', 's10'],
  PGUPAST:['pers', 'gen-', 'guk en pasado: nosotros.', 's10'],
  PL3:    ['pers', '-ir- / -z', 'NOR plural de 3.ª persona: ellos, ellas (dira, doaz).', 's9'],
  PLTE:   ['pers', '-te', 'Plural: zuek (vosotros) o haiek (ellos, como agente).', 's9'],
  PLZTE:  ['pers', '-zte', 'haiek (agente) cuando el objeto es plural: dituzte.', 's10'],
  KT:     ['pers', '-t / -da-', 'ni / nik / niri: yo, a mí. Si le sigue otro sufijo, -t pasa a -da- (dida-zu, duda-la).', 's10'],
  KZU:    ['pers', '-zu', 'zu / zuk / zuri: tú, a ti.', 's10'],
  KGU:    ['pers', '-gu', 'gu / guk / guri: nosotros, a nosotros.', 's10'],
  KZUE:   ['pers', '-zue', 'zuek / zuei: vosotros, a vosotros.', 's10'],
  KTE:    ['pers', '-te', 'haiek: ellos / ellas (agente).', 's10'],
  KO:     ['pers', '-o', 'NORI hari: a él, a ella (se lo, le).', 's13'],
  KE:     ['pers', '-e', 'NORI haiei: a ellos, a ellas (les).', 's13'],
  DAT:    ['pers', '-i-', 'En el auxiliar hay un NORI (objeto indirecto).', 's13'],
  IT:     ['pers', '-it-', 'El objeto (NOR) es plural: dut → ditut (lo tengo → los tengo).', 's10'],
  ZKI:    ['pers', '-zki-', 'NOR plural cuando también hay NORI: diot → dizkiot, zait → zaizkit.', 's13'],
  PAST:   ['pers', '-(e)n', 'Pasado: el auxiliar termina en -n (nuen, zen, ginen).', 's9'],
  // ── partículas y subordinación
  EZ:     ['part', 'ez', 'Negación. Se pega al auxiliar y los dos pasan delante del verbo.', 's15'],
  BA:     ['part', 'ba-', 'Afirmativo con verbos sintéticos cuando van solos: badago, badakit.', 's15'],
  BAC:    ['part', 'ba-', 'Condicional «si …»: baduzu = si tienes / si quieres.', 's19'],
  AL:     ['part', 'al', 'Partícula de pregunta de sí o no: Etorriko al zara?', 's15'],
  LA:     ['part', '-(e)la', 'Completiva «que …»: uste dut berandu dela = creo que es tarde.', 's19'],
  NIND:   ['part', '-(e)n', 'Interrogativa indirecta: ez dakit non dagoen = no sé dónde está.', 's19'],
  NEAN:   ['part', '-(e)nean', 'Temporal «cuando …»: etortzen naizenean.', 's19'],
  LAKO:   ['part', '-(e)lako', 'Causal «porque …»: nekatuta nagoelako.', 's19']
};
